name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First action started
        run: echo 'This is first github action'
      - name: Completed first action
        run: echo 'Completed first github action'
        
        
